import "oaidl.idl";
import "ocidl.idl";
import "inspectable.idl";

[uuid(A0AD4485-702B-44B6-B48E-F82240EBBAEF)]
interface IHutaoNativeWindowNonRude : IInspectable
{
    HRESULT Attach();
    HRESULT Detach();
};
