import "oaidl.idl";
import "ocidl.idl";
import "Types.idl";

[uuid(D8E6C944-C964-4909-8BFF-901C40670DFF)]
interface IHutaoNativeLogicalDrive : IUnknown
{
    HRESULT GetDiskFreeSpace([in] PCWSTR path, [out] long* bytes);
};
