import "oaidl.idl";
import "ocidl.idl";
import "inspectable.idl";

import "Types.idl";
import "IHutaoString.idl";

[uuid(8C776674-9910-4721-A764-97BDB791F719)]
interface IHutaoNativeHotKeyAction : IInspectable
{
    HRESULT Update([in] int modifiers, [in] uint vk);
    HRESULT GetIsEnabled([out] BOOL* isEnabled);
    HRESULT SetIsEnabled([in] BOOL isEnabled);
}