import "oaidl.idl";
import "ocidl.idl";
import "inspectable.idl";
import "IHutaoString.idl";

[uuid(8607ACE4-313C-4C26-B1FB-CA11173B6953)]
interface IHutaoNativeLoopbackSupport : IInspectable
{
	HRESULT IsEnabled([in] HSTRING familyName, [in] IHutaoString* sid, [out, retval] boolean* enabled);
	HRESULT Enable([in] HSTRING familyName, [in] IHutaoString* sid);
}