import "oaidl.idl";
import "ocidl.idl";
import "types.idl";
import "IHutaoString.idl";
import "IHutaoNativeLoopbackSupport.idl";
import "IHutaoNativeRegistryNotification.idl";
import "IHutaoNativeWindowSubclass.idl";
import "IHutaoNativeWindowNonRude.idl";
import "IHutaoNativeDeviceCapabilities.idl";
import "IHutaoNativePhysicalDrive.idl";
import "IHutaoNativeLogicalDrive.idl";
import "IHutaoNativeInputLowLevelKeyboardSource.idl";
import "IHutaoNativeFileSystem.idl";
import "IHutaoNativeNotifyIcon.idl";
import "IHutaoNativeHotKeyAction.idl";
import "IHutaoNativeProcess.idl";

[uuid(1A6980D9-EB36-4E3E-86E7-3665C57C6E8D)]
interface IHutaoNativePrivate : IUnknown
{
	HRESULT IsCurrentWindowsVersionSupported([out] BOOL* isSupported);
	HRESULT GetWindowsVersion([out] HutaoPrivateWindowsVersion* pv);
	HRESULT ShowErrorMessage([in] PCWSTR title, [in] PCWSTR message);
};

[uuid(4E5D37CF-5F38-4FF2-9059-DF39CA696365)]
interface IHutaoPrivate2 : IUnknown
{
	HRESULT ExchangeGameUidForIdentifier1820([in] PCWSTR gameUid, [out] byte* identifier);
};

[uuid(D00F73FF-A1C7-4091-8CB6-D90991DD40CB)]
interface IHutaoNative : IUnknown
{
	HRESULT MakeLoopbackSupport([out] IHutaoNativeLoopbackSupport** ppv);
	HRESULT MakeRegistryNotification([in] PCWSTR keyPath, [out] IHutaoNativeRegistryNotification** ppv);
	HRESULT MakeWindowSubclass([in] INT64 hWnd, [in] nint callback, [in] INT64 userData, [out] IHutaoNativeWindowSubclass** ppv);
	HRESULT MakeWindowNonRude([in] INT64 hWnd, [out] IHutaoNativeWindowNonRude** ppv);
};

[uuid(338487EE-9592-4171-89DD-1E6B9EDB2C8E)]
interface IHutaoNative2 : IUnknown
{
	HRESULT MakeDeviceCapabilities([out] IHutaoNativeDeviceCapabilities** ppv);
	HRESULT MakePhysicalDrive([out] IHutaoNativePhysicalDrive** ppv);
	HRESULT MakeLogicalDrive([out] IHutaoNativeLogicalDrive** ppv);
};

[uuid(135FACE1-3184-4D12-B4D0-21FFB6A88D25)]
interface IHutaoNative3 : IUnknown
{
	HRESULT MakeInputLowLevelKeyboardSource([out] IHutaoNativeInputLowLevelKeyboardSource** ppv);
};

[uuid(27942FBE-322F-4157-9B8C-A38FDB827B05)]
interface IHutaoNative4 : IUnknown
{
	HRESULT MakeFileSystem([out] IHutaoNativeFileSystem** ppv);
};

[uuid(7B4D20F1-4DAD-492E-8485-B4701A2ED19B)]
interface IHutaoNative5 : IUnknown
{
	HRESULT MakeNotifyIcon([in] PCWSTR iconPath, [in] GUID* id, [out] IHutaoNativeNotifyIcon** ppv);
};

[uuid(B68CABFA-C55A-49FA-8C51-21615C594E2B)]
interface IHutaoNative6 : IUnknown
{
	HRESULT MakeHotKeyAction([in] HutaoNativeHotKeyActionKind kind, [in] nint callback, [in] nint userData, [out] IHutaoNativeHotKeyAction** ppv);
};

[uuid(B7A49A20-D9E2-43FD-9637-E80190443ABE)]
interface IHutaoNative7 : IUnknown
{
	HRESULT MakeProcess([in] HutaoNativeProcessStartInfo info, [out] IHutaoNativeProcess** ppv);
};
